/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bookshopmanagementsystem;

import bookshopmanagementsystem.interfaces.Book;
import bookshopmanagementsystem.interfaces.Cart;
import java.util.List;
import javax.swing.JPanel;


/**
 *
 * @author Wiktor
 */
public class CartPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClientPanel
     */
    private MainFrame mainFrame;
    public CartPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        Cart.getInstance().setUpdateListener(this::refreshCartItems);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanel = new javax.swing.JPanel();
        HelloLabel = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        OrdersBtn = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        CartItemsLabel = new javax.swing.JLabel();
        CartItemsPanel = new javax.swing.JPanel();
        CartItemsScrollPane = new javax.swing.JScrollPane();
        CartItemsBoxPanel = new javax.swing.JPanel();
        CartSummaryPanel = new javax.swing.JPanel();
        TotalValueInfoLabel = new javax.swing.JLabel();
        OrderBtn = new javax.swing.JButton();
        TotalValueLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setLayout(new java.awt.BorderLayout());

        SidePanel.setPreferredSize(new java.awt.Dimension(150, 485));
        SidePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        HelloLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HelloLabel.setText("Your Cart");
        SidePanel.add(HelloLabel);
        HelloLabel.getAccessibleContext().setAccessibleDescription("");

        BackBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.setPreferredSize(new java.awt.Dimension(80, 30));
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        SidePanel.add(BackBtn);

        OrdersBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OrdersBtn.setText("Orders");
        OrdersBtn.setPreferredSize(new java.awt.Dimension(80, 30));
        OrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdersBtnActionPerformed(evt);
            }
        });
        SidePanel.add(OrdersBtn);

        LogOutBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogOutBtn.setText("Log out");
        LogOutBtn.setPreferredSize(new java.awt.Dimension(85, 30));
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });
        SidePanel.add(LogOutBtn);

        add(SidePanel, java.awt.BorderLayout.LINE_START);

        MainPanel.setMaximumSize(new java.awt.Dimension(750, 385));
        MainPanel.setPreferredSize(new java.awt.Dimension(750, 385));

        HeaderPanel.setPreferredSize(new java.awt.Dimension(750, 80));
        HeaderPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 60, 30));

        CartItemsLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        CartItemsLabel.setText("Cart Items");
        HeaderPanel.add(CartItemsLabel);

        MainPanel.add(HeaderPanel);

        CartItemsPanel.setPreferredSize(new java.awt.Dimension(740, 350));
        CartItemsPanel.setLayout(new javax.swing.BoxLayout(CartItemsPanel, javax.swing.BoxLayout.LINE_AXIS));

        CartItemsScrollPane.setPreferredSize(new java.awt.Dimension(690, 485));

        CartItemsBoxPanel.setLayout(new javax.swing.BoxLayout(CartItemsBoxPanel, javax.swing.BoxLayout.Y_AXIS));
        CartItemsScrollPane.setViewportView(CartItemsBoxPanel);

        CartItemsPanel.add(CartItemsScrollPane);

        MainPanel.add(CartItemsPanel);

        CartSummaryPanel.setPreferredSize(new java.awt.Dimension(770, 100));
        CartSummaryPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 200, 5));

        TotalValueInfoLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TotalValueInfoLabel.setText("Total Value:");
        CartSummaryPanel.add(TotalValueInfoLabel);

        OrderBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OrderBtn.setText("Order");
        OrderBtn.setPreferredSize(new java.awt.Dimension(110, 40));
        CartSummaryPanel.add(OrderBtn);

        TotalValueLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TotalValueLabel.setText("0 ZŁ");
        CartSummaryPanel.add(TotalValueLabel);

        MainPanel.add(CartSummaryPanel);

        add(MainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        mainFrame.showPanel("client");
    }//GEN-LAST:event_BackBtnActionPerformed

    private void OrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdersBtnActionPerformed

    }//GEN-LAST:event_OrdersBtnActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        mainFrame.showPanel("login");
    }//GEN-LAST:event_LogOutBtnActionPerformed
     public JPanel getCartItemsBoxPanel() {
        return CartItemsBoxPanel;
    }

     private void refreshCartItems() {
         CartItemsBoxPanel.removeAll();
          List<Book> books = Cart.getInstance().getItems();
            for (Book book : books) {
                JPanel cartItemPanel = new CartItemPanel(book);
                CartItemsBoxPanel.add(cartItemPanel);
            }
            TotalValueLabel.setText(Cart.getInstance().getTotalValue() + " ZŁ");
            CartItemsBoxPanel.revalidate();
            CartItemsBoxPanel.repaint();
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JPanel CartItemsBoxPanel;
    private javax.swing.JLabel CartItemsLabel;
    private javax.swing.JPanel CartItemsPanel;
    private javax.swing.JScrollPane CartItemsScrollPane;
    private javax.swing.JPanel CartSummaryPanel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel HelloLabel;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton OrderBtn;
    private javax.swing.JButton OrdersBtn;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JLabel TotalValueInfoLabel;
    private javax.swing.JLabel TotalValueLabel;
    // End of variables declaration//GEN-END:variables
}
