/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example;

import com.example.dto.BookDto;
import com.example.dto.IdDto;
import com.example.dto.NewBookDto;
import com.example.requests.AddBookRequest;
import com.example.requests.DeleteBookRequest;
import com.example.requests.UpdateBookRequest;

import java.awt.event.MouseListener;
import java.math.BigDecimal;

/**
 *
 * @author Wiktor
 */
public class BookAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookPanel
     */
    private AdminPanel adminPanel;
    private MainFrame mainFrame;
    private BookDto book;

    public BookAdminPanel(BookDto book, AdminPanel adminPanel, MainFrame mainFrame) {
        initComponents();
        TitleLabel.setText(book.getTitle());
        AuthorLabel.setText(book.getAuthor());
        PriceLabel.setText(String.valueOf(book.getPrice()) + " ZŁ");
        this.adminPanel = adminPanel;
        this.mainFrame = mainFrame;
        this.book = book;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImagePanel = new javax.swing.JPanel();
        ImageLabel = new javax.swing.JLabel();
        BookInfoPanel = new javax.swing.JPanel();
        TitlePanel = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        AuthorPanel = new javax.swing.JPanel();
        AuthorLabel = new javax.swing.JLabel();
        PricePanel = new javax.swing.JPanel();
        PriceLabel = new javax.swing.JLabel();
        BtnPanel = new javax.swing.JPanel();
        EditBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 15, 1), javax.swing.BorderFactory.createTitledBorder("")));
        setMaximumSize(new java.awt.Dimension(250, 420));
        setPreferredSize(new java.awt.Dimension(250, 420));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        ImagePanel.setPreferredSize(new java.awt.Dimension(218, 200));
        ImagePanel.setLayout(new java.awt.BorderLayout());

        ImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/no-image-icon-23485.png"))); // NOI18N
        ImagePanel.add(ImageLabel, java.awt.BorderLayout.CENTER);

        add(ImagePanel);

        BookInfoPanel.setPreferredSize(new java.awt.Dimension(218, 120));
        BookInfoPanel.setLayout(new javax.swing.BoxLayout(BookInfoPanel, javax.swing.BoxLayout.Y_AXIS));

        TitlePanel.setPreferredSize(new java.awt.Dimension(225, 30));
        TitlePanel.setLayout(new java.awt.BorderLayout());

        TitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Title");
        TitleLabel.setToolTipText("");
        TitlePanel.add(TitleLabel, java.awt.BorderLayout.CENTER);

        BookInfoPanel.add(TitlePanel);

        AuthorPanel.setPreferredSize(new java.awt.Dimension(225, 30));
        AuthorPanel.setLayout(new java.awt.BorderLayout());

        AuthorLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AuthorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AuthorLabel.setText("Author");
        AuthorPanel.add(AuthorLabel, java.awt.BorderLayout.CENTER);

        BookInfoPanel.add(AuthorPanel);

        PricePanel.setPreferredSize(new java.awt.Dimension(225, 30));
        PricePanel.setLayout(new java.awt.BorderLayout());

        PriceLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PriceLabel.setText("Price");
        PricePanel.add(PriceLabel, java.awt.BorderLayout.CENTER);

        BookInfoPanel.add(PricePanel);

        add(BookInfoPanel);

        BtnPanel.setPreferredSize(new java.awt.Dimension(218, 50));

        EditBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditBtn.setText("Edit");
        EditBtn.setPreferredSize(new java.awt.Dimension(110, 30));
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });
        BtnPanel.add(EditBtn);

        DeleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteBtn.setText("Delete");
        DeleteBtn.setPreferredSize(new java.awt.Dimension(110, 30));
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        BtnPanel.add(DeleteBtn);

        add(BtnPanel);
    }// </editor-fold>//GEN-END:initComponents


    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        BookFormPanel bookFormPanel = new BookFormPanel(mainFrame,book);
        mainFrame.mainPanel.add(bookFormPanel,"bookEditForm");
        mainFrame.showPanel("bookEditForm");
        bookFormPanel.getAddButton().setText("Edit");
        bookFormPanel.getTitleLabel().setText("Edit Book");
        MouseListener[] listeners = bookFormPanel.getAddButton().getMouseListeners();
        for (MouseListener listener : listeners) {
            bookFormPanel.getAddButton().removeMouseListener(listener);
        }
        bookFormPanel.getAddButton().addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String title = bookFormPanel.getTitleTextField().getText();
                String author = bookFormPanel.getAuthorTextField().getText();
                String priceText = bookFormPanel.getPriceTextField().getText();
                BigDecimal price = new BigDecimal(priceText);

                if (!title.isEmpty() && !author.isEmpty() && !priceText.isEmpty()) {
                    BookDto updatedBookDto = new BookDto(book.id,title, author, price);
                    UpdateBookRequest updateBookRequest = new UpdateBookRequest(updatedBookDto);

                    try {
                        Client client = BookShopManagementSystem.getClient();
                        if (client != null) {
                            String response = client.sendMessage(updateBookRequest.create());
                            System.out.println("Server response: " + response);
                        } else {
                            System.out.println("Client is not connected.");
                        }
                    } catch (Exception e) {
                        System.out.println(e);
                    }

                    bookFormPanel.getInfoLabel().setForeground(new java.awt.Color(40, 252, 3));
                    bookFormPanel.getInfoLabel().setText("Book edited!");
                } else {
                    bookFormPanel.getInfoLabel().setForeground(new java.awt.Color(255, 51, 51));
                    bookFormPanel.getInfoLabel().setText("Fill all field!");
                }
            }
        });

    }//GEN-LAST:event_EditBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        DeleteBookRequest deleteBookRequest = new DeleteBookRequest(new IdDto(book.id));
        try {
            Client client = BookShopManagementSystem.getClient();
            if (client != null) {
                String response = client.sendMessage(deleteBookRequest.create());
                System.out.println("Server response: " + response);
                adminPanel.refreshBooksBoxPanel();
            }   else {
                System.out.println("Client is not connected.");
            }
        }catch(Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AuthorLabel;
    private javax.swing.JPanel AuthorPanel;
    private javax.swing.JPanel BookInfoPanel;
    private javax.swing.JPanel BtnPanel;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JPanel ImagePanel;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JPanel PricePanel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JPanel TitlePanel;
    // End of variables declaration//GEN-END:variables
}
