/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example;

import bookshopmanagementsystem.interfaces.Cart;
import com.example.interfaces.BookInCart;
import java.util.List;
import javax.swing.JPanel;


/**
 * CartPanel represents the user interface for the shopping cart in the application.
 * It provides functionalities to view cart items, their total value, and proceed to the order form.
 * It listens for updates to the cart and refreshes the cart contents and total value accordingly.
 * 
 * @author Wiktor
 */
public class CartPanel extends javax.swing.JPanel {
    
    private MainFrame mainFrame;
     /**
     * Creates a new CartPanel for displaying the cart information.
     * Initializes the panel and sets up listeners to update the cart items and total value.
     *
     * @param mainFrame the main frame containing the cart panel.
     */
    public CartPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        Cart.getInstance().setUpdateListener(this::refreshCartItems);
        Cart.getInstance().setUpdateValueListener(this::refreshCartValue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanel = new javax.swing.JPanel();
        HelloLabel = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        OrdersBtn = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        CartItemsLabel = new javax.swing.JLabel();
        CartItemsPanel = new javax.swing.JPanel();
        CartItemsScrollPane = new javax.swing.JScrollPane();
        CartItemsBoxPanel = new javax.swing.JPanel();
        CartSummaryPanel = new javax.swing.JPanel();
        TotalValueInfoLabel = new javax.swing.JLabel();
        OrderBtn = new javax.swing.JButton();
        TotalValueLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setLayout(new java.awt.BorderLayout());

        SidePanel.setPreferredSize(new java.awt.Dimension(150, 485));
        SidePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        HelloLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HelloLabel.setText("Your Cart");
        SidePanel.add(HelloLabel);
        HelloLabel.getAccessibleContext().setAccessibleDescription("");

        BackBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.setPreferredSize(new java.awt.Dimension(80, 30));
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        SidePanel.add(BackBtn);

        OrdersBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OrdersBtn.setText("Orders");
        OrdersBtn.setPreferredSize(new java.awt.Dimension(80, 30));
        OrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdersBtnActionPerformed(evt);
            }
        });
        SidePanel.add(OrdersBtn);

        LogOutBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogOutBtn.setText("Log out");
        LogOutBtn.setPreferredSize(new java.awt.Dimension(85, 30));
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });
        SidePanel.add(LogOutBtn);

        add(SidePanel, java.awt.BorderLayout.LINE_START);

        MainPanel.setMaximumSize(new java.awt.Dimension(750, 385));
        MainPanel.setPreferredSize(new java.awt.Dimension(750, 385));

        HeaderPanel.setPreferredSize(new java.awt.Dimension(750, 80));
        HeaderPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 60, 30));

        CartItemsLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        CartItemsLabel.setText("Cart Items");
        HeaderPanel.add(CartItemsLabel);

        MainPanel.add(HeaderPanel);

        CartItemsPanel.setPreferredSize(new java.awt.Dimension(600, 350));
        CartItemsPanel.setLayout(new javax.swing.BoxLayout(CartItemsPanel, javax.swing.BoxLayout.LINE_AXIS));

        CartItemsScrollPane.setPreferredSize(new java.awt.Dimension(690, 485));

        CartItemsBoxPanel.setLayout(new javax.swing.BoxLayout(CartItemsBoxPanel, javax.swing.BoxLayout.Y_AXIS));
        CartItemsScrollPane.setViewportView(CartItemsBoxPanel);

        CartItemsPanel.add(CartItemsScrollPane);

        MainPanel.add(CartItemsPanel);

        CartSummaryPanel.setPreferredSize(new java.awt.Dimension(770, 100));
        CartSummaryPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 200, 5));

        TotalValueInfoLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TotalValueInfoLabel.setText("Total Value:");
        CartSummaryPanel.add(TotalValueInfoLabel);

        OrderBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OrderBtn.setText("Order");
        OrderBtn.setPreferredSize(new java.awt.Dimension(110, 40));
        OrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderBtnActionPerformed(evt);
            }
        });
        CartSummaryPanel.add(OrderBtn);

        TotalValueLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TotalValueLabel.setText("0 ZŁ");
        CartSummaryPanel.add(TotalValueLabel);

        MainPanel.add(CartSummaryPanel);

        add(MainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Handles the event when the "Back" button is clicked.
     * Navigates back to the previous panel (Client Panel).
     * 
     * @param evt the action event that triggered this method.
     */
    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        mainFrame.showPanel("client");
    }//GEN-LAST:event_BackBtnActionPerformed
    /**
     * Handles the event when the "Orders" button is clicked.
     * Navigates to the Orders panel.
     * 
     * @param evt the action event that triggered this method.
     */
    private void OrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdersBtnActionPerformed
        mainFrame.showPanel("orders");
    }//GEN-LAST:event_OrdersBtnActionPerformed
    /**
     * Handles the event when the "Log Out" button is clicked.
     * Navigates to the Login panel.
     * 
     * @param evt the action event that triggered this method.
     */
    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        mainFrame.showPanel("login");
    }//GEN-LAST:event_LogOutBtnActionPerformed
    /**
     * Handles the event when the "Order" button is clicked.
     * Navigates to the order form and populates it with the books currently in the cart.
     * 
     * @param evt the action event that triggered this method.
     */
    private void OrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderBtnActionPerformed
        
        
        List<BookInCart> booksInCart = Cart.getInstance().getItems();
        OrderFormPanel orderFormPanel = new OrderFormPanel(mainFrame,booksInCart);
        mainFrame.mainPanel.add(orderFormPanel, "ordersForm");
        orderFormPanel.getTotalValueLabel().setText(String.valueOf(Cart.getInstance().getTotalValue()) + "ZŁ");
        for (BookInCart book : booksInCart) {
                BookInfoPanel bookInfoPanel = new BookInfoPanel(book,mainFrame);
                orderFormPanel.getOrderItemsBoxPanel().add(bookInfoPanel);
            }
        mainFrame.showPanel("ordersForm");
    }//GEN-LAST:event_OrderBtnActionPerformed
     
     /**
     * Returns the panel containing the cart items.
     * 
     * @return the panel containing the cart items.
     */
    public JPanel getCartItemsBoxPanel() {
        return CartItemsBoxPanel;
    }
    
    /**
     * Refreshes the cart items displayed in the cart panel.
     * This method is triggered when the cart is updated, and it updates the UI with the current items in the cart.
     */
     private void refreshCartItems() {
         CartItemsBoxPanel.removeAll();
          List<BookInCart> books = Cart.getInstance().getItems();
            for (BookInCart book : books) {
                JPanel cartItemPanel = new CartItemPanel(book);
                CartItemsBoxPanel.add(cartItemPanel);
            }
            TotalValueLabel.setText(Cart.getInstance().getTotalValue() + " ZŁ");
            CartItemsBoxPanel.revalidate();
            CartItemsBoxPanel.repaint();
     }
     
     /**
     * Refreshes the total value label when the total value of the cart changes.
     * This method is triggered when the cart's value is updated, reflecting the new total amount.
     */
     private void refreshCartValue(){
         TotalValueLabel.setText(Cart.getInstance().getTotalValue() + " ZŁ");
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JPanel CartItemsBoxPanel;
    private javax.swing.JLabel CartItemsLabel;
    private javax.swing.JPanel CartItemsPanel;
    private javax.swing.JScrollPane CartItemsScrollPane;
    private javax.swing.JPanel CartSummaryPanel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel HelloLabel;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton OrderBtn;
    private javax.swing.JButton OrdersBtn;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JLabel TotalValueInfoLabel;
    private javax.swing.JLabel TotalValueLabel;
    // End of variables declaration//GEN-END:variables
}
