/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example;

import com.example.dto.OrderDto;

/**
 *
 * @author Wiktor
 */
public class OrderItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderAdminPanel
     */
    MainFrame mainFrame;
    OrderDto order;
    public OrderItemPanel(OrderDto order, MainFrame mainFrame) {
        initComponents();
        IdLabel.setText("ID: " + String.valueOf(order.id));
        StreetLabel.setText("Street: " +order.street);
        CityLabel.setText("City: " + order.city);
        ZipLabel.setText("Zip: " +order.zip);
        DateLabel.setText("Date: " +order.date);
        StatusLabel.setText("Status: " + order.status);
        this.mainFrame = mainFrame;
        this.order = order;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OrderInfoPanel = new javax.swing.JPanel();
        IdPanel = new javax.swing.JPanel();
        IdLabel = new javax.swing.JLabel();
        StreetPanel = new javax.swing.JPanel();
        StreetLabel = new javax.swing.JLabel();
        CityPanel = new javax.swing.JPanel();
        CityLabel = new javax.swing.JLabel();
        ZipPanel = new javax.swing.JPanel();
        ZipLabel = new javax.swing.JLabel();
        DatePanel = new javax.swing.JPanel();
        DateLabel = new javax.swing.JLabel();
        StatusPanel = new javax.swing.JPanel();
        StatusLabel = new javax.swing.JLabel();
        BtnPanel = new javax.swing.JPanel();
        Details = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        OrderInfoPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createTitledBorder("")));
        OrderInfoPanel.setPreferredSize(new java.awt.Dimension(250, 431));
        OrderInfoPanel.setLayout(new javax.swing.BoxLayout(OrderInfoPanel, javax.swing.BoxLayout.Y_AXIS));

        IdPanel.setPreferredSize(new java.awt.Dimension(225, 10));
        IdPanel.setLayout(new java.awt.BorderLayout());

        IdLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IdLabel.setText("ID");
        IdLabel.setToolTipText("");
        IdLabel.setPreferredSize(new java.awt.Dimension(38, 20));
        IdPanel.add(IdLabel, java.awt.BorderLayout.CENTER);

        OrderInfoPanel.add(IdPanel);

        StreetPanel.setPreferredSize(new java.awt.Dimension(225, 30));
        StreetPanel.setLayout(new java.awt.BorderLayout());

        StreetLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        StreetLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StreetLabel.setText("STREET");
        StreetPanel.add(StreetLabel, java.awt.BorderLayout.CENTER);

        OrderInfoPanel.add(StreetPanel);

        CityPanel.setPreferredSize(new java.awt.Dimension(225, 30));
        CityPanel.setLayout(new java.awt.BorderLayout());

        CityLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CityLabel.setText("CITY");
        CityPanel.add(CityLabel, java.awt.BorderLayout.CENTER);

        OrderInfoPanel.add(CityPanel);

        ZipPanel.setPreferredSize(new java.awt.Dimension(225, 30));
        ZipPanel.setLayout(new java.awt.BorderLayout());

        ZipLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ZipLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ZipLabel.setText("ZIP");
        ZipPanel.add(ZipLabel, java.awt.BorderLayout.CENTER);

        OrderInfoPanel.add(ZipPanel);

        DatePanel.setPreferredSize(new java.awt.Dimension(225, 30));
        DatePanel.setLayout(new java.awt.BorderLayout());

        DateLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DateLabel.setText("DATE");
        DatePanel.add(DateLabel, java.awt.BorderLayout.CENTER);

        OrderInfoPanel.add(DatePanel);

        StatusPanel.setPreferredSize(new java.awt.Dimension(225, 10));
        StatusPanel.setLayout(new java.awt.BorderLayout());

        StatusLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        StatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StatusLabel.setText("STATUS");
        StatusLabel.setToolTipText("");
        StatusLabel.setPreferredSize(new java.awt.Dimension(38, 20));
        StatusPanel.add(StatusLabel, java.awt.BorderLayout.CENTER);

        OrderInfoPanel.add(StatusPanel);

        BtnPanel.setPreferredSize(new java.awt.Dimension(218, 50));

        Details.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Details.setText("Details");
        Details.setPreferredSize(new java.awt.Dimension(110, 30));
        Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailsActionPerformed(evt);
            }
        });
        BtnPanel.add(Details);

        OrderInfoPanel.add(BtnPanel);

        add(OrderInfoPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailsActionPerformed
        OrderDetailsPanel orderDetailsPanel = new OrderDetailsPanel(mainFrame,order);
        mainFrame.mainPanel.add(orderDetailsPanel, "orderDetail");
        mainFrame.showPanel("orderDetail");
    }//GEN-LAST:event_DetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnPanel;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JPanel CityPanel;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JPanel DatePanel;
    private javax.swing.JButton Details;
    private javax.swing.JLabel IdLabel;
    private javax.swing.JPanel IdPanel;
    private javax.swing.JPanel OrderInfoPanel;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JPanel StatusPanel;
    private javax.swing.JLabel StreetLabel;
    private javax.swing.JPanel StreetPanel;
    private javax.swing.JLabel ZipLabel;
    private javax.swing.JPanel ZipPanel;
    // End of variables declaration//GEN-END:variables
}
