/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example;



/**
 *
 * @author Wiktor
 */
public class OrdersPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClientPanel
     */
    private MainFrame mainFrame;
    public OrdersPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanel = new javax.swing.JPanel();
        HelloLabel = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        CartBtn = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        OrderItemsLabel = new javax.swing.JLabel();
        OrderItemsPanel = new javax.swing.JPanel();
        OrderItemsScrollPane = new javax.swing.JScrollPane();
        OrderItemsBoxPanel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setLayout(new java.awt.BorderLayout());

        SidePanel.setPreferredSize(new java.awt.Dimension(150, 485));
        SidePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        HelloLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HelloLabel.setText("Your Orders");
        SidePanel.add(HelloLabel);
        HelloLabel.getAccessibleContext().setAccessibleDescription("");

        BackBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.setPreferredSize(new java.awt.Dimension(80, 30));
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        SidePanel.add(BackBtn);

        CartBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CartBtn.setText("Cart");
        CartBtn.setPreferredSize(new java.awt.Dimension(80, 30));
        CartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartBtnActionPerformed(evt);
            }
        });
        SidePanel.add(CartBtn);

        LogOutBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogOutBtn.setText("Log out");
        LogOutBtn.setPreferredSize(new java.awt.Dimension(85, 30));
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });
        SidePanel.add(LogOutBtn);

        add(SidePanel, java.awt.BorderLayout.LINE_START);

        MainPanel.setMaximumSize(new java.awt.Dimension(750, 385));
        MainPanel.setPreferredSize(new java.awt.Dimension(750, 385));

        HeaderPanel.setPreferredSize(new java.awt.Dimension(750, 80));
        HeaderPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 60, 30));

        OrderItemsLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        OrderItemsLabel.setText("Orders");
        HeaderPanel.add(OrderItemsLabel);

        MainPanel.add(HeaderPanel);

        OrderItemsPanel.setPreferredSize(new java.awt.Dimension(600, 350));
        OrderItemsPanel.setLayout(new javax.swing.BoxLayout(OrderItemsPanel, javax.swing.BoxLayout.LINE_AXIS));

        OrderItemsScrollPane.setPreferredSize(new java.awt.Dimension(690, 485));

        OrderItemsBoxPanel.setLayout(new javax.swing.BoxLayout(OrderItemsBoxPanel, javax.swing.BoxLayout.Y_AXIS));
        OrderItemsScrollPane.setViewportView(OrderItemsBoxPanel);

        OrderItemsPanel.add(OrderItemsScrollPane);

        MainPanel.add(OrderItemsPanel);

        add(MainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        mainFrame.showPanel("client");
    }//GEN-LAST:event_BackBtnActionPerformed

    private void CartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartBtnActionPerformed
        mainFrame.showPanel("cart");
    }//GEN-LAST:event_CartBtnActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        mainFrame.showPanel("login");
    }//GEN-LAST:event_LogOutBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton CartBtn;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel HelloLabel;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel OrderItemsBoxPanel;
    private javax.swing.JLabel OrderItemsLabel;
    private javax.swing.JPanel OrderItemsPanel;
    private javax.swing.JScrollPane OrderItemsScrollPane;
    private javax.swing.JPanel SidePanel;
    // End of variables declaration//GEN-END:variables
}
