/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example;

import com.example.dto.OrderDto;
import com.example.dto.OrderStatus;
import com.example.dto.UpdateOrderStatusDto;
import com.example.requests.UpdateOrderStatusRequest;
import com.example.responses.Response;
import com.example.responses.ResponseType;
import com.example.responses.SelectBooksResponse;

/**
 *
 * @author Wiktor
 */
public class OrderAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderAdminPanel
     */
    OrderDto order;
    MainFrame mainFrame;
    AdminOrdersPanel adminOrdersPanel;
    public OrderAdminPanel(OrderDto order, MainFrame mainFrame, AdminOrdersPanel adminOrdersPanel) {
        initComponents();
        this.order = order;
        IdLabel.setText("Order ID: " +  String.valueOf(order.id));
        StreetLabel.setText("Street: " + order.street);
        CityLabel.setText("City: " +order.city);
        ZipLabel.setText("Zip: " +order.zip);
        DateLabel.setText("Order Date: " +order.date);
        UserIdLabel.setText("User ID: " + String.valueOf(order.userId));
        StatusComboBox.setSelectedItem(OrderStatus.toString(order.status));
        this.mainFrame = mainFrame;
        this.adminOrdersPanel = adminOrdersPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OrderInfoPanel = new javax.swing.JPanel();
        IdPanel = new javax.swing.JPanel();
        IdLabel = new javax.swing.JLabel();
        StreetPanel = new javax.swing.JPanel();
        StreetLabel = new javax.swing.JLabel();
        CityPanel = new javax.swing.JPanel();
        CityLabel = new javax.swing.JLabel();
        ZipPanel = new javax.swing.JPanel();
        ZipLabel = new javax.swing.JLabel();
        DatePanel = new javax.swing.JPanel();
        DateLabel = new javax.swing.JLabel();
        StatusPanel = new javax.swing.JPanel();
        StatusComboBox = new javax.swing.JComboBox<>();
        UserIdPanel = new javax.swing.JPanel();
        UserIdLabel = new javax.swing.JLabel();
        BtnPanel = new javax.swing.JPanel();
        EditStatusBtn = new javax.swing.JButton();
        Details = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createTitledBorder("")));
        setMinimumSize(new java.awt.Dimension(250, 490));
        setPreferredSize(new java.awt.Dimension(250, 490));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        OrderInfoPanel.setMinimumSize(new java.awt.Dimension(218, 180));
        OrderInfoPanel.setPreferredSize(new java.awt.Dimension(218, 180));
        OrderInfoPanel.setLayout(new javax.swing.BoxLayout(OrderInfoPanel, javax.swing.BoxLayout.Y_AXIS));

        IdPanel.setPreferredSize(new java.awt.Dimension(225, 30));
        IdPanel.setLayout(new java.awt.BorderLayout());

        IdLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IdLabel.setText("ID");
        IdPanel.add(IdLabel, java.awt.BorderLayout.CENTER);

        OrderInfoPanel.add(IdPanel);

        StreetPanel.setPreferredSize(new java.awt.Dimension(225, 30));
        StreetPanel.setLayout(new java.awt.BorderLayout());

        StreetLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        StreetLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StreetLabel.setText("STREET");
        StreetPanel.add(StreetLabel, java.awt.BorderLayout.CENTER);

        OrderInfoPanel.add(StreetPanel);

        CityPanel.setPreferredSize(new java.awt.Dimension(225, 30));
        CityPanel.setLayout(new java.awt.BorderLayout());

        CityLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CityLabel.setText("CITY");
        CityPanel.add(CityLabel, java.awt.BorderLayout.CENTER);

        OrderInfoPanel.add(CityPanel);

        ZipPanel.setPreferredSize(new java.awt.Dimension(225, 30));
        ZipPanel.setLayout(new java.awt.BorderLayout());

        ZipLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ZipLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ZipLabel.setText("ZIP");
        ZipPanel.add(ZipLabel, java.awt.BorderLayout.CENTER);

        OrderInfoPanel.add(ZipPanel);

        DatePanel.setPreferredSize(new java.awt.Dimension(225, 30));
        DatePanel.setLayout(new java.awt.BorderLayout());

        DateLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DateLabel.setText("DATE");
        DatePanel.add(DateLabel, java.awt.BorderLayout.CENTER);

        OrderInfoPanel.add(DatePanel);

        StatusPanel.setLayout(new java.awt.BorderLayout());

        StatusComboBox.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        StatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "InPreparation", "Sent", "Delivered" }));
        StatusPanel.add(StatusComboBox, java.awt.BorderLayout.CENTER);

        UserIdPanel.setPreferredSize(new java.awt.Dimension(225, 30));
        UserIdPanel.setLayout(new java.awt.BorderLayout());

        UserIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UserIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserIdLabel.setText("UserId");
        UserIdPanel.add(UserIdLabel, java.awt.BorderLayout.CENTER);

        StatusPanel.add(UserIdPanel, java.awt.BorderLayout.PAGE_START);

        OrderInfoPanel.add(StatusPanel);

        BtnPanel.setPreferredSize(new java.awt.Dimension(218, 50));

        EditStatusBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditStatusBtn.setText("Edit Status");
        EditStatusBtn.setPreferredSize(new java.awt.Dimension(110, 30));
        EditStatusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditStatusBtnActionPerformed(evt);
            }
        });
        BtnPanel.add(EditStatusBtn);

        Details.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Details.setText("Details");
        Details.setPreferredSize(new java.awt.Dimension(110, 30));
        Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailsActionPerformed(evt);
            }
        });
        BtnPanel.add(Details);

        OrderInfoPanel.add(BtnPanel);

        add(OrderInfoPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void EditStatusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditStatusBtnActionPerformed
        String newStatus = StatusComboBox.getSelectedItem().toString();
        if (!newStatus.isEmpty()) {
            
            UpdateOrderStatusDto updateOrderStatusDto = new UpdateOrderStatusDto(order.id, OrderStatus.fromString(newStatus));
            UpdateOrderStatusRequest updateOrderStatusRequest = new UpdateOrderStatusRequest(updateOrderStatusDto);

            try {
                Client client = BookShopManagementSystem.getClient();
                    if (client != null) {
                        String response = client.sendMessage(updateOrderStatusRequest.create());
                        System.out.println("Server response: " + response);
                        String[] result = Response.split(response);
                        if((ResponseType.fromResponseHeader(result[0]) == ResponseType.Ok)) {
                            Toast toast = new Toast(adminOrdersPanel, "Status Edited", 1000);
                        }else{
                            ToastFailed toastFailed = new ToastFailed(adminOrdersPanel, "Status Edit failed", 1000);
                            
                        }
                    }else{
                        System.out.println("Client is not connected.");
                        }
                    }catch (Exception e) {
                        System.out.println(e);
                    }
        }

    }//GEN-LAST:event_EditStatusBtnActionPerformed

    private void DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailsActionPerformed
        OrderAdminDetailsPanel orderAdminDetailsPanel = new OrderAdminDetailsPanel(mainFrame,order);
        mainFrame.mainPanel.add(orderAdminDetailsPanel, "orderAdminDetail");
        mainFrame.showPanel("orderAdminDetail");
    }//GEN-LAST:event_DetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnPanel;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JPanel CityPanel;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JPanel DatePanel;
    private javax.swing.JButton Details;
    private javax.swing.JButton EditStatusBtn;
    private javax.swing.JLabel IdLabel;
    private javax.swing.JPanel IdPanel;
    private javax.swing.JPanel OrderInfoPanel;
    private javax.swing.JComboBox<String> StatusComboBox;
    private javax.swing.JPanel StatusPanel;
    private javax.swing.JLabel StreetLabel;
    private javax.swing.JPanel StreetPanel;
    private javax.swing.JLabel UserIdLabel;
    private javax.swing.JPanel UserIdPanel;
    private javax.swing.JLabel ZipLabel;
    private javax.swing.JPanel ZipPanel;
    // End of variables declaration//GEN-END:variables
}
