/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example;

/**
 *
 * @author Wiktor
 */
public class OrderFormPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderFormPanel
     */
    private MainFrame mainFrame;
    public OrderFormPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OrderPanel = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        LogInLabel = new javax.swing.JLabel();
        OrderFormPanel = new javax.swing.JPanel();
        NamePanel = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        LastNamePanel = new javax.swing.JPanel();
        LastNameLabel = new javax.swing.JLabel();
        LastNameTextField = new javax.swing.JTextField();
        EmailPanel = new javax.swing.JPanel();
        EmailLabel = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        StreetPanel = new javax.swing.JPanel();
        StreetLabel = new javax.swing.JLabel();
        StreetField = new javax.swing.JPasswordField();
        CityPanel = new javax.swing.JPanel();
        CityLabel = new javax.swing.JLabel();
        CityField = new javax.swing.JPasswordField();
        ZipPanel = new javax.swing.JPanel();
        ZipLabel = new javax.swing.JLabel();
        ZipField = new javax.swing.JPasswordField();
        infoPanel = new javax.swing.JPanel();
        InfoLabel = new javax.swing.JLabel();
        OrderBtnPanel = new javax.swing.JPanel();
        OrderButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        SidePanel = new javax.swing.JPanel();
        OrderItemsPanel = new javax.swing.JPanel();
        OrderItemsScrollPane = new javax.swing.JScrollPane();
        OrderItemsBoxPanel = new javax.swing.JPanel();
        OrderSummaryPanel = new javax.swing.JPanel();
        TotalValueInfoLabel = new javax.swing.JLabel();
        TotalValueLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(200, 62));
        setLayout(new java.awt.BorderLayout());

        OrderPanel.setPreferredSize(new java.awt.Dimension(400, 0));

        HeaderPanel.setPreferredSize(new java.awt.Dimension(400, 100));

        LogInLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LogInLabel.setText("Order");

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(LogInLabel)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(LogInLabel)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        OrderPanel.add(HeaderPanel);

        OrderFormPanel.setPreferredSize(new java.awt.Dimension(400, 380));

        NamePanel.setPreferredSize(new java.awt.Dimension(280, 50));
        NamePanel.setLayout(new java.awt.BorderLayout(4, 4));

        NameLabel.setText("Name");
        NamePanel.add(NameLabel, java.awt.BorderLayout.PAGE_START);

        NameTextField.setPreferredSize(new java.awt.Dimension(64, 25));
        NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextFieldActionPerformed(evt);
            }
        });
        NamePanel.add(NameTextField, java.awt.BorderLayout.CENTER);

        OrderFormPanel.add(NamePanel);

        LastNamePanel.setPreferredSize(new java.awt.Dimension(280, 50));
        LastNamePanel.setLayout(new java.awt.BorderLayout(4, 4));

        LastNameLabel.setText("Last Name");
        LastNamePanel.add(LastNameLabel, java.awt.BorderLayout.PAGE_START);

        LastNameTextField.setPreferredSize(new java.awt.Dimension(64, 25));
        LastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextFieldActionPerformed(evt);
            }
        });
        LastNamePanel.add(LastNameTextField, java.awt.BorderLayout.CENTER);

        OrderFormPanel.add(LastNamePanel);

        EmailPanel.setPreferredSize(new java.awt.Dimension(280, 50));
        EmailPanel.setLayout(new java.awt.BorderLayout(4, 4));

        EmailLabel.setText("Email Address");
        EmailPanel.add(EmailLabel, java.awt.BorderLayout.PAGE_START);

        EmailTextField.setPreferredSize(new java.awt.Dimension(64, 25));
        EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextFieldActionPerformed(evt);
            }
        });
        EmailPanel.add(EmailTextField, java.awt.BorderLayout.CENTER);

        OrderFormPanel.add(EmailPanel);

        StreetPanel.setPreferredSize(new java.awt.Dimension(280, 50));
        StreetPanel.setLayout(new java.awt.BorderLayout(4, 4));

        StreetLabel.setText("Street");
        StreetPanel.add(StreetLabel, java.awt.BorderLayout.PAGE_START);

        StreetField.setPreferredSize(new java.awt.Dimension(64, 25));
        StreetField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StreetFieldActionPerformed(evt);
            }
        });
        StreetPanel.add(StreetField, java.awt.BorderLayout.CENTER);

        OrderFormPanel.add(StreetPanel);

        CityPanel.setPreferredSize(new java.awt.Dimension(280, 50));
        CityPanel.setLayout(new java.awt.BorderLayout(4, 4));

        CityLabel.setText("City");
        CityPanel.add(CityLabel, java.awt.BorderLayout.PAGE_START);

        CityField.setPreferredSize(new java.awt.Dimension(64, 25));
        CityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityFieldActionPerformed(evt);
            }
        });
        CityPanel.add(CityField, java.awt.BorderLayout.CENTER);

        OrderFormPanel.add(CityPanel);

        ZipPanel.setPreferredSize(new java.awt.Dimension(280, 50));
        ZipPanel.setLayout(new java.awt.BorderLayout(4, 4));

        ZipLabel.setText("Zip");
        ZipPanel.add(ZipLabel, java.awt.BorderLayout.PAGE_START);

        ZipField.setPreferredSize(new java.awt.Dimension(64, 25));
        ZipField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZipFieldActionPerformed(evt);
            }
        });
        ZipPanel.add(ZipField, java.awt.BorderLayout.CENTER);

        OrderFormPanel.add(ZipPanel);

        infoPanel.setPreferredSize(new java.awt.Dimension(280, 50));
        infoPanel.setLayout(new java.awt.BorderLayout(4, 4));

        InfoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InfoLabel.setForeground(new java.awt.Color(255, 51, 51));
        infoPanel.add(InfoLabel, java.awt.BorderLayout.CENTER);

        OrderFormPanel.add(infoPanel);

        OrderPanel.add(OrderFormPanel);

        OrderBtnPanel.setPreferredSize(new java.awt.Dimension(400, 50));

        OrderButton.setText("Order");
        OrderButton.setPreferredSize(new java.awt.Dimension(150, 30));
        OrderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderButtonMouseClicked(evt);
            }
        });
        OrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderButtonActionPerformed(evt);
            }
        });
        OrderBtnPanel.add(OrderButton);

        BackButton.setText("Back");
        BackButton.setPreferredSize(new java.awt.Dimension(150, 30));
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        OrderBtnPanel.add(BackButton);

        OrderPanel.add(OrderBtnPanel);

        add(OrderPanel, java.awt.BorderLayout.LINE_START);

        SidePanel.setPreferredSize(new java.awt.Dimension(400, 420));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        SidePanel.setLayout(flowLayout1);

        OrderItemsPanel.setPreferredSize(new java.awt.Dimension(500, 500));
        OrderItemsPanel.setLayout(new javax.swing.BoxLayout(OrderItemsPanel, javax.swing.BoxLayout.LINE_AXIS));

        OrderItemsScrollPane.setPreferredSize(new java.awt.Dimension(690, 485));

        OrderItemsBoxPanel.setLayout(new javax.swing.BoxLayout(OrderItemsBoxPanel, javax.swing.BoxLayout.Y_AXIS));
        OrderItemsScrollPane.setViewportView(OrderItemsBoxPanel);

        OrderItemsPanel.add(OrderItemsScrollPane);

        SidePanel.add(OrderItemsPanel);

        OrderSummaryPanel.setPreferredSize(new java.awt.Dimension(770, 100));
        OrderSummaryPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 200, 5));

        TotalValueInfoLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TotalValueInfoLabel.setText("Total Value:");
        OrderSummaryPanel.add(TotalValueInfoLabel);

        TotalValueLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TotalValueLabel.setText("0 ZŁ");
        OrderSummaryPanel.add(TotalValueLabel);

        SidePanel.add(OrderSummaryPanel);

        add(SidePanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldActionPerformed

    private void LastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextFieldActionPerformed

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    private void StreetFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StreetFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StreetFieldActionPerformed

    private void CityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityFieldActionPerformed

    private void OrderButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderButtonMouseClicked
        String name = NameTextField.getText();
        String lastName = LastNameTextField.getText();
        String email = EmailTextField.getText();
        String password = new String(StreetField.getPassword());
        String repeatPassword = new String(CityField.getPassword());

        if(!password.equals(repeatPassword)) {
            InfoLabel.setForeground(new java.awt.Color(255, 51, 51));
            InfoLabel.setText("Passwords are not the same.");
        }else{
            InfoLabel.setText("");
            NameTextField.setText("");
            LastNameTextField.setText("");
            EmailTextField.setText("");
            StreetField.setText("");
            CityField.setText("");
            InfoLabel.setForeground(new java.awt.Color(40, 252, 3));
            InfoLabel.setText("Success you have been registered!");

        }

    }//GEN-LAST:event_OrderButtonMouseClicked

    private void OrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderButtonActionPerformed

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        mainFrame.showPanel("client");
    }//GEN-LAST:event_BackButtonMouseClicked

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ZipFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZipFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZipFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JPasswordField CityField;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JPanel CityPanel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JPanel EmailPanel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel InfoLabel;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JPanel LastNamePanel;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JLabel LogInLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JPanel NamePanel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JPanel OrderBtnPanel;
    private javax.swing.JButton OrderButton;
    private javax.swing.JPanel OrderFormPanel;
    private javax.swing.JPanel OrderItemsBoxPanel;
    private javax.swing.JPanel OrderItemsPanel;
    private javax.swing.JScrollPane OrderItemsScrollPane;
    private javax.swing.JPanel OrderPanel;
    private javax.swing.JPanel OrderSummaryPanel;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JPasswordField StreetField;
    private javax.swing.JLabel StreetLabel;
    private javax.swing.JPanel StreetPanel;
    private javax.swing.JLabel TotalValueInfoLabel;
    private javax.swing.JLabel TotalValueLabel;
    private javax.swing.JPasswordField ZipField;
    private javax.swing.JLabel ZipLabel;
    private javax.swing.JPanel ZipPanel;
    private javax.swing.JPanel infoPanel;
    // End of variables declaration//GEN-END:variables
}
