/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example;

/**
 *
 * @author Wiktor
 */
public class OrderAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderAdminPanel
     */
    public OrderAdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OrderInfoPanel = new javax.swing.JPanel();
        IdPanel = new javax.swing.JPanel();
        IdLabel = new javax.swing.JLabel();
        StreetPanel = new javax.swing.JPanel();
        StreetLabel = new javax.swing.JLabel();
        CityPanel = new javax.swing.JPanel();
        CityLabel = new javax.swing.JLabel();
        ZipPanel = new javax.swing.JPanel();
        ZipLabel = new javax.swing.JLabel();
        DatePanel = new javax.swing.JPanel();
        DateLabel = new javax.swing.JLabel();
        UserIdPanel = new javax.swing.JPanel();
        UserIdLabel = new javax.swing.JLabel();
        StatusPanel = new javax.swing.JPanel();
        StatusComboBox = new javax.swing.JComboBox<>();
        BtnPanel = new javax.swing.JPanel();
        EditStatusBtn = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        OrderInfoPanel.setPreferredSize(new java.awt.Dimension(218, 120));
        OrderInfoPanel.setLayout(new javax.swing.BoxLayout(OrderInfoPanel, javax.swing.BoxLayout.Y_AXIS));

        IdPanel.setPreferredSize(new java.awt.Dimension(225, 10));
        IdPanel.setLayout(new java.awt.BorderLayout());

        IdLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IdLabel.setText("ID");
        IdLabel.setToolTipText("");
        IdLabel.setPreferredSize(new java.awt.Dimension(38, 20));
        IdPanel.add(IdLabel, java.awt.BorderLayout.CENTER);

        OrderInfoPanel.add(IdPanel);

        StreetPanel.setPreferredSize(new java.awt.Dimension(225, 30));
        StreetPanel.setLayout(new java.awt.BorderLayout());

        StreetLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        StreetLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StreetLabel.setText("STREET");
        StreetPanel.add(StreetLabel, java.awt.BorderLayout.CENTER);

        OrderInfoPanel.add(StreetPanel);

        CityPanel.setPreferredSize(new java.awt.Dimension(225, 30));
        CityPanel.setLayout(new java.awt.BorderLayout());

        CityLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CityLabel.setText("CITY");
        CityPanel.add(CityLabel, java.awt.BorderLayout.CENTER);

        OrderInfoPanel.add(CityPanel);

        ZipPanel.setPreferredSize(new java.awt.Dimension(225, 30));
        ZipPanel.setLayout(new java.awt.BorderLayout());

        ZipLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ZipLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ZipLabel.setText("ZIP");
        ZipPanel.add(ZipLabel, java.awt.BorderLayout.CENTER);

        OrderInfoPanel.add(ZipPanel);

        DatePanel.setPreferredSize(new java.awt.Dimension(225, 30));
        DatePanel.setLayout(new java.awt.BorderLayout());

        DateLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DateLabel.setText("DATE");
        DatePanel.add(DateLabel, java.awt.BorderLayout.CENTER);

        OrderInfoPanel.add(DatePanel);

        UserIdPanel.setPreferredSize(new java.awt.Dimension(225, 10));
        UserIdPanel.setLayout(new java.awt.BorderLayout());

        UserIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UserIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserIdLabel.setText("USERID");
        UserIdLabel.setToolTipText("");
        UserIdLabel.setPreferredSize(new java.awt.Dimension(38, 20));
        UserIdPanel.add(UserIdLabel, java.awt.BorderLayout.CENTER);

        OrderInfoPanel.add(UserIdPanel);

        StatusPanel.setLayout(new java.awt.BorderLayout());

        StatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STATUS" }));
        StatusPanel.add(StatusComboBox, java.awt.BorderLayout.CENTER);

        OrderInfoPanel.add(StatusPanel);

        BtnPanel.setPreferredSize(new java.awt.Dimension(218, 50));

        EditStatusBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditStatusBtn.setText("Edit Status");
        EditStatusBtn.setPreferredSize(new java.awt.Dimension(110, 30));
        EditStatusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditStatusBtnActionPerformed(evt);
            }
        });
        BtnPanel.add(EditStatusBtn);

        OrderInfoPanel.add(BtnPanel);

        add(OrderInfoPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void EditStatusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditStatusBtnActionPerformed

    }//GEN-LAST:event_EditStatusBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnPanel;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JPanel CityPanel;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JPanel DatePanel;
    private javax.swing.JButton EditStatusBtn;
    private javax.swing.JLabel IdLabel;
    private javax.swing.JPanel IdPanel;
    private javax.swing.JPanel OrderInfoPanel;
    private javax.swing.JComboBox<String> StatusComboBox;
    private javax.swing.JPanel StatusPanel;
    private javax.swing.JLabel StreetLabel;
    private javax.swing.JPanel StreetPanel;
    private javax.swing.JLabel UserIdLabel;
    private javax.swing.JPanel UserIdPanel;
    private javax.swing.JLabel ZipLabel;
    private javax.swing.JPanel ZipPanel;
    // End of variables declaration//GEN-END:variables
}
