/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example;

import com.example.dto.NewUserDto;
import com.example.requests.AddUserDto;
import com.example.requests.AddUserRequest;


/**
 *
 * @author Wiktor
 */
public class UserFormPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserFormPanel
     */
    MainFrame mainFrame;

    public UserFormPanel(MainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddUserPanel = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        AddUserLabel = new javax.swing.JLabel();
        AddUserFormPanel = new javax.swing.JPanel();
        NamePanel = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        LastNamePanel = new javax.swing.JPanel();
        LastNameLabel = new javax.swing.JLabel();
        LastNameTextField = new javax.swing.JTextField();
        EmailPanel = new javax.swing.JPanel();
        EmailLabel = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        PasswordPanel = new javax.swing.JPanel();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        RolePanel = new javax.swing.JPanel();
        RoleLabel = new javax.swing.JLabel();
        RoleComboBox = new javax.swing.JComboBox<>();
        infoPanel = new javax.swing.JPanel();
        InfoLabel = new javax.swing.JLabel();
        AddUserBtnPanel = new javax.swing.JPanel();
        AddUserButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        AddUserPanel.setPreferredSize(new java.awt.Dimension(400, 0));

        HeaderPanel.setPreferredSize(new java.awt.Dimension(400, 100));

        AddUserLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AddUserLabel.setText("Add User");

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(AddUserLabel)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(AddUserLabel)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        AddUserPanel.add(HeaderPanel);

        AddUserFormPanel.setPreferredSize(new java.awt.Dimension(400, 330));

        NamePanel.setPreferredSize(new java.awt.Dimension(280, 50));
        NamePanel.setLayout(new java.awt.BorderLayout(4, 4));

        NameLabel.setText("Name");
        NamePanel.add(NameLabel, java.awt.BorderLayout.PAGE_START);

        NameTextField.setPreferredSize(new java.awt.Dimension(64, 25));
        NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextFieldActionPerformed(evt);
            }
        });
        NamePanel.add(NameTextField, java.awt.BorderLayout.CENTER);

        AddUserFormPanel.add(NamePanel);

        LastNamePanel.setPreferredSize(new java.awt.Dimension(280, 50));
        LastNamePanel.setLayout(new java.awt.BorderLayout(4, 4));

        LastNameLabel.setText("Last Name");
        LastNamePanel.add(LastNameLabel, java.awt.BorderLayout.PAGE_START);

        LastNameTextField.setPreferredSize(new java.awt.Dimension(64, 25));
        LastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextFieldActionPerformed(evt);
            }
        });
        LastNamePanel.add(LastNameTextField, java.awt.BorderLayout.CENTER);

        AddUserFormPanel.add(LastNamePanel);

        EmailPanel.setPreferredSize(new java.awt.Dimension(280, 50));
        EmailPanel.setLayout(new java.awt.BorderLayout(4, 4));

        EmailLabel.setText("Email Address");
        EmailPanel.add(EmailLabel, java.awt.BorderLayout.PAGE_START);

        EmailTextField.setPreferredSize(new java.awt.Dimension(64, 25));
        EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextFieldActionPerformed(evt);
            }
        });
        EmailPanel.add(EmailTextField, java.awt.BorderLayout.CENTER);

        AddUserFormPanel.add(EmailPanel);

        PasswordPanel.setPreferredSize(new java.awt.Dimension(280, 50));
        PasswordPanel.setLayout(new java.awt.BorderLayout(4, 4));

        PasswordLabel.setText("Password");
        PasswordPanel.add(PasswordLabel, java.awt.BorderLayout.PAGE_START);

        PasswordField.setPreferredSize(new java.awt.Dimension(64, 25));
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        PasswordPanel.add(PasswordField, java.awt.BorderLayout.CENTER);

        AddUserFormPanel.add(PasswordPanel);

        RolePanel.setPreferredSize(new java.awt.Dimension(280, 50));
        RolePanel.setLayout(new java.awt.BorderLayout(4, 4));

        RoleLabel.setText("Role");
        RolePanel.add(RoleLabel, java.awt.BorderLayout.PAGE_START);

        RoleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));
        RolePanel.add(RoleComboBox, java.awt.BorderLayout.CENTER);

        AddUserFormPanel.add(RolePanel);

        infoPanel.setPreferredSize(new java.awt.Dimension(280, 50));
        infoPanel.setLayout(new java.awt.BorderLayout(4, 4));

        InfoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InfoLabel.setForeground(new java.awt.Color(255, 51, 51));
        infoPanel.add(InfoLabel, java.awt.BorderLayout.CENTER);

        AddUserFormPanel.add(infoPanel);

        AddUserPanel.add(AddUserFormPanel);

        AddUserBtnPanel.setPreferredSize(new java.awt.Dimension(400, 50));

        AddUserButton.setText("Add");
        AddUserButton.setPreferredSize(new java.awt.Dimension(150, 30));
        AddUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddUserButtonMouseClicked(evt);
            }
        });
        AddUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserButtonActionPerformed(evt);
            }
        });
        AddUserBtnPanel.add(AddUserButton);

        BackButton.setText("Back");
        BackButton.setPreferredSize(new java.awt.Dimension(150, 30));
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        AddUserBtnPanel.add(BackButton);

        AddUserPanel.add(AddUserBtnPanel);

        add(AddUserPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldActionPerformed

    private void LastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextFieldActionPerformed

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void AddUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddUserButtonMouseClicked
        String name = NameTextField.getText();
        String lastName = LastNameTextField.getText();
        String email = EmailTextField.getText();
        String password = new String(PasswordField.getPassword());
        String fullName = name + " " + lastName;

        NewUserDto newUserDto = new NewUserDto(fullName, email, password);
        AddUserRequest addUserRequest = new AddUserRequest(newUserDto);

        try {
            Client client = BookShopManagementSystem.getClient();
            if (client != null) {
                String response = client.sendMessage(addUserRequest.create());
                System.out.println("Server response: " + response);
            } else {
                System.out.println("Client is not connected.");
            }
        } catch (Exception e) {
            System.out.println(e);
        }

        InfoLabel.setText("");
        NameTextField.setText("");
        LastNameTextField.setText("");
        EmailTextField.setText("");
        PasswordField.setText("");
        InfoLabel.setForeground(new java.awt.Color(40, 252, 3));
        InfoLabel.setText("User Added!");


    }//GEN-LAST:event_AddUserButtonMouseClicked

    private void AddUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddUserButtonActionPerformed

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        mainFrame.showPanel("adminUsers");
    }//GEN-LAST:event_BackButtonMouseClicked

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        mainFrame.showPanel("adminUsers");
    }//GEN-LAST:event_BackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddUserBtnPanel;
    private javax.swing.JButton AddUserButton;
    private javax.swing.JPanel AddUserFormPanel;
    private javax.swing.JLabel AddUserLabel;
    private javax.swing.JPanel AddUserPanel;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JPanel EmailPanel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel InfoLabel;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JPanel LastNamePanel;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JPanel NamePanel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPanel PasswordPanel;
    private javax.swing.JComboBox<String> RoleComboBox;
    private javax.swing.JLabel RoleLabel;
    private javax.swing.JPanel RolePanel;
    private javax.swing.JPanel infoPanel;
    // End of variables declaration//GEN-END:variables
}
