/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example;

import com.example.dto.NewUserWithRoleDto;
import com.example.dto.Role;
import com.example.dto.UserDto;
import com.example.requests.AddUserWithRoleRequest;

/**
 * UserFormPanel is a JPanel that provides a graphical user interface (GUI) for adding or editing a user's information.
 * This panel allows the user to enter their name, last name, email, password, and role.
 * It also handles the submission of the form to add the user, and displays a confirmation message or error if validation fails.
 * 
 * @author Wiktor
 */
public class UserFormPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserFormPanel
     */
    MainFrame mainFrame;
    Role[] roles;
    UserDto user;
    
    
     /**
     * Constructs a new UserFormPanel for adding a user.
     * 
     * @param mainFrame The main frame of the application.
     */
    public UserFormPanel(MainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;

    }

    
     /**
     * Constructs a new UserFormPanel for editing an existing user.
     * 
     * @param mainFrame The main frame of the application.
     * @param user The user data to pre-fill the form.
     */
    public UserFormPanel(MainFrame mainFrame, UserDto user) {
        initComponents();
        this.mainFrame = mainFrame;
        this.user = user;
        String[] parts = user.name.split(" ");
        NameTextField.setText(parts[0]);
        LastNameTextField.setText(parts[1]);
        EmailTextField.setText(user.email);
        PasswordField.setText(user.password);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddUserPanel = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        AddUserLabel = new javax.swing.JLabel();
        AddUserFormPanel = new javax.swing.JPanel();
        NamePanel = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        LastNamePanel = new javax.swing.JPanel();
        LastNameLabel = new javax.swing.JLabel();
        LastNameTextField = new javax.swing.JTextField();
        EmailPanel = new javax.swing.JPanel();
        EmailLabel = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        PasswordPanel = new javax.swing.JPanel();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        RolePanel = new javax.swing.JPanel();
        RoleLabel = new javax.swing.JLabel();
        RoleComboBox = new javax.swing.JComboBox<>();
        infoPanel = new javax.swing.JPanel();
        InfoLabel = new javax.swing.JLabel();
        AddUserBtnPanel = new javax.swing.JPanel();
        AddUserButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        AddUserPanel.setPreferredSize(new java.awt.Dimension(400, 0));

        HeaderPanel.setPreferredSize(new java.awt.Dimension(400, 100));

        AddUserLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AddUserLabel.setText("Add User");

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(AddUserLabel)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(AddUserLabel)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        AddUserPanel.add(HeaderPanel);

        AddUserFormPanel.setPreferredSize(new java.awt.Dimension(400, 330));

        NamePanel.setPreferredSize(new java.awt.Dimension(280, 50));
        NamePanel.setLayout(new java.awt.BorderLayout(4, 4));

        NameLabel.setText("Name");
        NamePanel.add(NameLabel, java.awt.BorderLayout.PAGE_START);

        NameTextField.setPreferredSize(new java.awt.Dimension(64, 25));
        NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextFieldActionPerformed(evt);
            }
        });
        NamePanel.add(NameTextField, java.awt.BorderLayout.CENTER);

        AddUserFormPanel.add(NamePanel);

        LastNamePanel.setPreferredSize(new java.awt.Dimension(280, 50));
        LastNamePanel.setLayout(new java.awt.BorderLayout(4, 4));

        LastNameLabel.setText("Last Name");
        LastNamePanel.add(LastNameLabel, java.awt.BorderLayout.PAGE_START);

        LastNameTextField.setPreferredSize(new java.awt.Dimension(64, 25));
        LastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextFieldActionPerformed(evt);
            }
        });
        LastNamePanel.add(LastNameTextField, java.awt.BorderLayout.CENTER);

        AddUserFormPanel.add(LastNamePanel);

        EmailPanel.setPreferredSize(new java.awt.Dimension(280, 50));
        EmailPanel.setLayout(new java.awt.BorderLayout(4, 4));

        EmailLabel.setText("Email Address");
        EmailPanel.add(EmailLabel, java.awt.BorderLayout.PAGE_START);

        EmailTextField.setPreferredSize(new java.awt.Dimension(64, 25));
        EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextFieldActionPerformed(evt);
            }
        });
        EmailPanel.add(EmailTextField, java.awt.BorderLayout.CENTER);

        AddUserFormPanel.add(EmailPanel);

        PasswordPanel.setPreferredSize(new java.awt.Dimension(280, 50));
        PasswordPanel.setLayout(new java.awt.BorderLayout(4, 4));

        PasswordLabel.setText("Password");
        PasswordPanel.add(PasswordLabel, java.awt.BorderLayout.PAGE_START);

        PasswordField.setPreferredSize(new java.awt.Dimension(64, 25));
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        PasswordPanel.add(PasswordField, java.awt.BorderLayout.CENTER);

        AddUserFormPanel.add(PasswordPanel);

        RolePanel.setPreferredSize(new java.awt.Dimension(280, 50));
        RolePanel.setLayout(new java.awt.BorderLayout(4, 4));

        RoleLabel.setText("Role");
        RolePanel.add(RoleLabel, java.awt.BorderLayout.PAGE_START);

        RoleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));
        RolePanel.add(RoleComboBox, java.awt.BorderLayout.CENTER);

        AddUserFormPanel.add(RolePanel);

        infoPanel.setPreferredSize(new java.awt.Dimension(280, 50));
        infoPanel.setLayout(new java.awt.BorderLayout(4, 4));

        InfoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InfoLabel.setForeground(new java.awt.Color(255, 51, 51));
        infoPanel.add(InfoLabel, java.awt.BorderLayout.CENTER);

        AddUserFormPanel.add(infoPanel);

        AddUserPanel.add(AddUserFormPanel);

        AddUserBtnPanel.setPreferredSize(new java.awt.Dimension(400, 50));

        AddUserButton.setText("Add");
        AddUserButton.setPreferredSize(new java.awt.Dimension(150, 30));
        AddUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddUserButtonMouseClicked(evt);
            }
        });
        AddUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserButtonActionPerformed(evt);
            }
        });
        AddUserBtnPanel.add(AddUserButton);

        BackButton.setText("Back");
        BackButton.setPreferredSize(new java.awt.Dimension(150, 30));
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        AddUserBtnPanel.add(BackButton);

        AddUserPanel.add(AddUserBtnPanel);

        add(AddUserPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldActionPerformed

    private void LastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextFieldActionPerformed

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void AddUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddUserButtonMouseClicked

    }//GEN-LAST:event_AddUserButtonMouseClicked
    /**
     * Handles the action when the AddUserButton is clicked.
     * It validates the form fields and sends a request to the server to add a new user.
     * If the user is added successfully, it clears the form and displays a success message.
     * 
     * @param evt The event triggered by the AddUserButton click.
     */
    private void AddUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserButtonActionPerformed
        String name = NameTextField.getText();
        String lastName = LastNameTextField.getText();
        String fullName = name + " " + lastName;
        String email = EmailTextField.getText();
        String password = new String(PasswordField.getPassword());
        String role = RoleComboBox.getSelectedItem().toString();

        if (!name.isEmpty() && !lastName.isEmpty() && !email.isEmpty() && !role.isEmpty()) {
            NewUserWithRoleDto newUserWithRoleDto = new NewUserWithRoleDto(fullName, email, password, Role.fromString(role));
            AddUserWithRoleRequest addUserWithRoleRequest = new AddUserWithRoleRequest(newUserWithRoleDto);

            try {
                Client client = BookShopManagementSystem.getClient();
                if (client != null) {
                    String response = client.sendMessage(addUserWithRoleRequest.create());
                    System.out.println("Server response: " + response);
                } else {
                    System.out.println("Client is not connected.");
                }
            } catch (Exception e) {
                System.out.println(e);
            }

            NameTextField.setText("");
            LastNameTextField.setText("");
            EmailTextField.setText("");
            PasswordField.setText("");
            InfoLabel.setForeground(new java.awt.Color(40, 252, 3));
            InfoLabel.setText("User added!");
        } else {
            InfoLabel.setForeground(new java.awt.Color(255, 51, 51));
            InfoLabel.setText("Fill all field!");
        }
    }//GEN-LAST:event_AddUserButtonActionPerformed

     /**
     * Handles the action when the BackButton is clicked.
     * It navigates back to the user management panel.
     * 
     * @param evt The event triggered by the BackButton click.
     */
    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        mainFrame.showPanel("adminUsers");
    }//GEN-LAST:event_BackButtonMouseClicked

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        mainFrame.showPanel("adminUsers");
    }//GEN-LAST:event_BackButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

    }//GEN-LAST:event_formComponentShown

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded

    }//GEN-LAST:event_formComponentAdded
    /**
     * Returns the AddUserButton component.
     * 
     * @return The AddUserButton.
     */
    public javax.swing.JButton getAddButton() {
        return AddUserButton;
    }
    /**
     * Returns the title label of the panel.
     * 
     * @return The AddUserLabel.
     */
    public javax.swing.JLabel getTitleLabel() {
        return AddUserLabel;
    }

     /**
     * Returns the text field for the user's first name.
     * 
     * @return The NameTextField.
     */
    public javax.swing.JTextField getNameTextField() {
        return NameTextField;
    }
    /**
     * Returns the text field for the user's last name.
     * 
     * @return The LastNameTextField.
     */
    public javax.swing.JTextField getLastNameTextField() {
        return LastNameTextField;
    }
    /**
     * Returns the text field for the user's email address.
     * 
     * @return The EmailTextField.
     */
    public javax.swing.JTextField getEmailTextField() {
        return EmailTextField;
    }
    /**
     * Returns the password field for the user's password.
     * 
     * @return The PasswordField.
     */
    public javax.swing.JPasswordField getPasswordField() {
        return PasswordField;
    }
    /**
     * Returns the combo box for selecting the user's role.
     * 
     * @return The RoleComboBox.
     */
    public javax.swing.JComboBox<String> getRoleComboBox() {
        return RoleComboBox;
    }
    /**
     * Returns the label displaying information about the form status (e.g., success or error).
     * 
     * @return The InfoLabel.
     */
    public javax.swing.JLabel getInfoLabel() {
        return InfoLabel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddUserBtnPanel;
    private javax.swing.JButton AddUserButton;
    private javax.swing.JPanel AddUserFormPanel;
    private javax.swing.JLabel AddUserLabel;
    private javax.swing.JPanel AddUserPanel;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JPanel EmailPanel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel InfoLabel;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JPanel LastNamePanel;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JPanel NamePanel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPanel PasswordPanel;
    private javax.swing.JComboBox<String> RoleComboBox;
    private javax.swing.JLabel RoleLabel;
    private javax.swing.JPanel RolePanel;
    private javax.swing.JPanel infoPanel;
    // End of variables declaration//GEN-END:variables
}
